Config = {}

-- Opções: 'auto' (detecção automática), 'vrp' (vRP Creative), 'qb' (QBCore), 'qbox' (QBox), 'esx' (ESX), 'standalone' (sem inventário, checa nativo do ped)
Config.Framework = 'qb'


Config.WeaponCategoryOffsets = {
    {category = 'handguns', bone = 11816, x = -0.01, y = 0.013, z = 0.22,  xRot = -90.0, yRot = 5.0,  zRot = -15.0},
    {category = 'waisthandgun', bone = 11816, x = -0.04, y = -0.015, z = 0.20,  xRot = -90.0, yRot = 17.0,  zRot = -13.0},
    {category = 'hiphandgun', bone = 51826, x = 0.05, y = -0.013, z = 0.12,  xRot = 275.0, yRot = 170.0,  zRot = -180.0},
    {category = 'handguns', bone = 6442, x = 0.05, y = -0.03, z = 0.12,  xRot = -110.0, yRot = -15.0,  zRot = -10.0},
    {category = 'boxers', bone = 11816, x = -0.03, y = 0.11, z = -0.07,  xRot = -210.0, yRot = 5.0,  zRot = -10.0},
    {category = 'revolver', bone = 11816, x = -0.08, y = 0.019, z = 0.22,  xRot = -90.0, yRot = 5.0,  zRot = -15.0},
    {category = 'bighandgun', bone = 11816, x = -0.04, y = 0.019, z = 0.22,  xRot = -90.0, yRot = 5.0,  zRot = -15.0},
    {category = 'utilityhandgun', bone = 11816, x = -0.12, y = 0.09,  z = -0.17, xRot = 135.0,  yRot = -13.50, zRot = -9.5},
    {category = 'smallmelee', bone = 11816, x = -0.15, y = -0.11, z = 0.17, xRot = 120.0, yRot = 90.0, zRot = 0.0},
    {category = 'bigmelee', bone = 11816, x = -0.15, y = -0.04, z = 0.20, xRot = 270.0, yRot = 90.0, zRot = 0.0},
    {category = 'utilitymelee', bone = 58271, x = 0.1, y = 0.1,  z = -0.15, xRot = -90.0,  yRot = 0.90, zRot = 90.0},
    {category = 'machine', bone = 24818, x = 0.09, y = -0.15, z = 0.1, xRot = 10.0, yRot = 160.0, zRot = 10.0},
    {category = 'assault', bone = 24818, x = 0.09, y = -0.15, z = 0.1, xRot = 10.0, yRot = 160.0, zRot = 10.0},
    {category = 'shotgun', bone = 24818, x = 0.09, y = -0.15, z = 0.1, xRot = 10.0, yRot = 160.0, zRot = 10.0},
    {category = 'sniper', bone = 24818, x = 0.09, y = -0.15, z = 0.1, xRot = 10.0, yRot = 160.0, zRot = 10.0},
    {category = 'heavy', bone = 24818, x = 0.09, y = -0.15, z = 0.1, xRot = 10.0, yRot = 160.0, zRot = 10.0},
    {category = 'bat', bone = 24816, x = 0.05, y = -0.15, z = 0.02, xRot = 0.0, yRot = 110.0, zRot = 0.0},
    {category = 'tacticalrifle', bone = 24818, x = 0.01, y = 0.22, z = 0.1, xRot = 200.0, yRot = 170.0, zRot = 10.0},
    {category = 'backhandgun', bone = 24816, x = -0.05, y = -0.15, z = -0.03, xRot = 180.0, yRot = 145.0, zRot = 0.0},
    {category = 'leghandgun', bone = 51826, x = 0.175, y = 0.02, z = 0.134,  xRot = -100.0, yRot = -0.0,  zRot = -13.0},
    {category = 'chesthandgun', bone = 24818, x = -0.0455, y = 0.040, z = 0.21, xRot = 262.0, yRot = 110.0, zRot = 5.0},
    {category = 'handguns2', bone = 51826, x = 0.07, y = 0.030, z = 0.156,  xRot = -105.0, yRot = -0.0,  zRot = -13.1},
}

Config.RealWeapons = {
    {name = 'WEAPON_KNIFE',             category = 'smallmelee',    model = 'prop_w_me_knife_01', canHide = false},
    {name = 'WEAPON_HAMMER',            category = 'utilitymelee',  model = 'prop_tool_hammer', canHide = false},
    {name = 'WEAPON_BAT',               category = 'bat',           model = 'w_me_bat', canHide = false},
    {name = 'WEAPON_GOLFCLUB',          category = 'bigmelee',      model = 'w_me_gclub', canHide = false},
    {name = 'WEAPON_CROWBAR',           category = 'utilitymelee',  model = 'w_me_crowbar', canHide = false},
    {name = 'WEAPON_BOTTLE',            category = 'smallmelee',    model = 'prop_w_me_bottle', canHide = false},
    {name = 'WEAPON_HATCHET',           category = 'bigmelee',      model = 'w_me_hatchet', canHide = false},
    {name = 'WEAPON_BATTLEAXE',         category = 'bigmelee',      model = 'w_me_battleaxe', canHide = false},
    {name = 'WEAPON_STONE_HATCHET',     category = 'bigmelee',      model = 'w_me_stonehatchet', canHide = false},
    {name = 'WEAPON_MACHETE',           category = 'bigmelee',      model = 'prop_ld_w_me_machette', canHide = false},
    {name = 'WEAPON_FLASHLIGHT',        category = 'utilitymelee',  model = nil, canHide = false},

    {name = 'WEAPON_PISTOL',            category = 'handguns',      model = 'w_pi_pistol', canHide = false},
    {name = 'WEAPON_COMBATPISTOL',      category = 'handguns',      model = 'w_pi_combatpistol', canHide = false},
    {name = 'WEAPON_APPISTOL',          category = 'handguns',      model = 'w_pi_appistol', canHide = false},
    {name = 'WEAPON_VINTAGEPISTOL',     category = 'handguns',      model = 'w_pi_vintage_pistol', canHide = false},
    {name = 'WEAPON_HEAVYPISTOL',       category = 'handguns',      model = 'w_pi_heavypistol', canHide = false},
    {name = 'WEAPON_FLAREGUN',          category = 'utilityhandgun',model = 'w_pi_flaregun', canHide = false},
    {name = 'WEAPON_REVOLVER',          category = 'revolver',      model = 'w_pi_revolver', canHide = false},
    {name = 'WEAPON_STUNGUN',           category = 'handguns',      model =  'w_pi_stungun',    canHide = false},

    {name = 'WEAPON_MICROSMG',          category = 'machine',   model = 'w_sb_microsmg', canHide = false},
    {name = 'WEAPON_UZI',               category = 'machine',   model = 'w_sb_microsmg', canHide = false},
    {name = 'WEAPON_MAC10',             category = 'machine',   model = 'w_sb_microsmg', canHide = false},
    {name = 'WEAPON_SMG',               category = 'machine',   model = 'w_sb_smg', canHide = false},
    {name = 'WEAPON_MG',                category = 'machine',   model = 'w_mg_mg', canHide = false},
    {name = 'WEAPON_COMBATMG',          category = 'machine',   model = 'w_mg_combatmg', canHide = false},
    {name = 'WEAPON_RPK17',             category = 'machine',   model = 'markomods-rpk16', canHide = false},
    {name = 'WEAPON_GUSENBERG',         category = 'machine',   model = 'w_sb_gusenberg', canHide = false},
    {name = 'WEAPON_MACHINEPISTOL',     category = 'machine',   model = 'w_sb_compactsmg', canHide = false},
    {name = 'WEAPON_MP9A',              category = 'machine',   model = 'w_sb_mp9a', canHide = false},

    {name = 'WEAPON_ASSAULTRIFLE',      category = 'assault',   model = 'w_ar_assaultrifle', canHide = false}, 
    {name = 'WEAPON_M70',               category = 'assault',   model = 'w_ar_m70', canHide = false}, 
    {name = 'WEAPON_SCARH',             category = 'assault',   model = 'w_ar_scarh', canHide = false}, 
    {name = 'WEAPON_AK47',              category = 'assault',   model = 'ak47', canHide = false}, 
    {name = 'WEAPON_AKS74M',            category = 'assault',   model = 'aks74m', canHide = false},
    {name = 'WEAPON_HK417',             category = 'assault',   model = 'chk416', canHide = false},
    {name = 'WEAPON_KS1',               category = 'assault',   model = 'w_ar_ks1', canHide = false},
    {name = 'WEAPON_LBRS',              category = 'assault',   model = 'w_ar_lbrs', canHide = false},
    {name = 'WEAPON_M4M203',            category = 'assault',   model = 'w_ar_m4m203', canHide = false},
    {name = 'WEAPON_MK18',              category = 'assault',   model = 'mk18', canHide = false},
    {name = 'WEAPON_SIG516',            category = 'assault',   model = 'sig516', canHide = false},
    {name = 'WEAPON_MK18B',             category = 'assault',   model = 'w_ar_mk18b', canHide = false},
    {name = 'WEAPON_ARX160',            category = 'assault',   model = 'w_ar_arx160', canHide = false},
    {name = 'WEAPON_CODACR',            category = 'assault',   model = 'w_ar_codacr', canHide = false},
    {name = 'WEAPON_HK33GOLD',          category = 'assault',   model = 'w_ar_hk33gold', canHide = false},
    {name = 'WEAPON_MONEYSCRB',         category = 'assault',   model = 'w_ar_moneyscrb', canHide = false},
    {name = 'WEAPON_CARBINERIFLE',      category = 'assault',   model = 'w_ar_carbinerifle', canHide = false},
    {name = 'WEAPON_ADVANCEDRIFLE',     category = 'assault',   model = 'w_ar_advancedrifle', canHide = false},
    {name = 'WEAPON_SPECIALCARBINE',    category = 'assault',   model = 'w_ar_specialcarbine', canHide = false},
    {name = 'WEAPON_BULLPUPRIFLE',      category = 'assault',   model = 'w_ar_bullpuprifle', canHide = false},
    {name = 'WEAPON_COMPACTRIFLE',      category = 'assault',   model = 'w_ar_assaultrifle_smg', canHide = false},

    {name = 'WEAPON_PUMPSHOTGUN',       category = 'shotgun',   model = 'w_sg_pumpshotgun', canHide = false},
    {name = 'WEAPON_MOSSBERG',          category = 'shotgun',   model = 'w_sg_mossberg', canHide = false},
    {name = 'WEAPON_SAWNOFFSHOTGUN',    category = 'shotgun',   model = 'w_sg_sawnoff', canHide = false},
    {name = 'WEAPON_BULLPUPSHOTGUN',    category = 'shotgun',   model = 'w_sg_bullpupshotgun', canHide = false},
    {name = 'WEAPON_ASSAULTSHOTGUN',    category = 'shotgun',   model = 'w_sg_assaultshotgun', canHide = false},
    {name = 'WEAPON_MUSKET',            category = 'shotgun',   model = 'w_ar_musket', canHide = false},
    {name = 'WEAPON_HEAVYSHOTGUN',      category = 'shotgun',   model = 'w_sg_heavyshotgun', canHide = false},
    {name = 'WEAPON_DBSHOTGUN',         category = 'shotgun',   model = 'w_sg_doublebarrel', canHide = false},
    {name = 'WEAPON_AUTOSHOTGUN',       category = 'shotgun',   model = 'w_sg_sweeper', canHide = false},

    {name = 'WEAPON_SNIPERRIFLE',       category = 'sniper',    model = 'w_sr_sniperrifle', canHide = false},
    {name = 'WEAPON_HEAVYSNIPER',       category = 'sniper',    model = 'w_sr_heavysniper', canHide = false},
    {name = 'WEAPON_MK14',              category = 'sniper',    model = 'w_sr_marksmanrifle', canHide = false},
    {name = 'WEAPON_HUNTINGRIFLE',      category = 'sniper',    model = 'w_sr_huntingrifle', canHide = false},
    {name = 'WEAPON_SVDM',              category = 'sniper',    model = 'svdm', canHide = false},
    {name = 'WEAPON_RPG',               category = 'backhandgun',model = 'w_lr_rpg', canHide = false},

    {name = 'WEAPON_STICKYBOMB',        category = 'thrown',    model = 'prop_bomb_01', canHide = false},
    {name = 'WEAPON_MOLOTOV',           category = 'thrown',    model = 'w_ex_molotov', canHide = false},
    {name = 'WEAPON_FIREEXTINGUISHER',  category = 'thrown',    model = 'w_am_fire_exting', canHide = false},
    {name = 'WEAPON_GRENADE',           category = 'thrown',    model = 'w_ex_grenadefrag', canHide = false},
    {name = 'WEAPON_SMOKEGRENADE',      category = 'thrown',    model = 'w_ex_grenadesmoke', canHide = false},
    {name = 'WEAPON_BZGAS',             category = 'thrown',    model = 'w_ex_grenadesmoke', canHide = false},

    {name = 'WEAPON_DIGISCANNER',       category = 'others',    model = 'w_am_digiscanner'},
    {name = 'WEAPON_DAGGER',            category = 'smallemelee', model = 'prop_w_me_dagger', canHide = false},
    {name = 'WEAPON_BATTLEAXE',         category = 'bigmelee',  model = 'prop_tool_fireaxe', canHide = false},
    {name = 'WEAPON_WRENCH',            category = 'bigmelee',  model = 'w_me_hammer', canHide = false},

    {name = 'WEAPON_PISTOL_MK2',        category = 'handguns',  model = 'w_pi_pistolmk2', canHide = false},
    {name = 'WEAPON_PUMPSHOTGUN_MK2',   category = 'shotgun',   model = 'w_sg_pumpshotgunmk2', canHide = false},
    {name = 'WEAPON_ASSAULTRIFLE_MK2',  category = 'assault',   model = 'w_ar_assaultriflemk2', canHide = false},
    {name = 'WEAPON_CARBINERIFLE_MK2',  category = 'assault',   model = 'w_ar_carbineriflemk2', canHide = false},
    {name = 'WEAPON_SPECIALCARBINE_MK2',category = 'assault',   model = 'w_ar_specialcarbinemk2', canHide = false},
    {name = 'WEAPON_BULLPUPRIFLE_MK2',  category = 'assault',   model = 'w_ar_bullpupriflemk2', canHide = false},
    {name = 'WEAPON_MILITARYRIFLE',     category = 'assault',   model = 'w_ar_militaryrifle', canHide = false},
    {name = 'WEAPON_HEAVYRIFLE',        category = 'assault',   model = 'w_ar_heavyrifle', canHide = false},
    {name = 'WEAPON_TACTICALRIFLE',     category = 'assault',   model = 'w_ar_tacticalrifle', canHide = false},
    {name = 'WEAPON_COMBATSHOTGUN',     category = 'shotgun',   model = 'w_sg_combatshotgun', canHide = false},
}
